name: Chatbot
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - docx2txt==0.9
      - flask==3.1.2
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - json-repair==0.44.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==1.1.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.0
      - langchain-neo4j==0.6.0
      - langchain-openai==1.1.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.10
      - langsmith==0.4.47
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mcp==1.22.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - neo4j==5.28.2
      - neo4j-graphrag==1.10.1
      - numpy==2.3.5
      - openai==2.8.1
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - propcache==0.4.1
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyjwt==2.10.1
      - pypdf==6.4.0
      - pypdf2==3.0.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.29.0
      - scipy==1.16.3
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sse-starlette==3.0.3
      - starlette==0.50.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - types-pyyaml==6.0.12.20250915
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /Users/distayy/miniconda3/envs/Chatbot
